import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/**
 * Flat config (ESLint 9).
 *
 * `eslint-config-next` still ships as eslintrc, so `FlatCompat` bridges it
 * rather than us hand-copying its rule set — a copy would silently go stale the
 * next time Next.js updates its recommendations.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      // Regenerated by `next build` on every run. Linting generated code means
      // the build fails until someone edits a file the tool will overwrite.
      'next-env.d.ts',
    ],
  },

  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  {
    rules: {
      /* ------------------------------------------------------------------
       * House rules that encode decisions taken elsewhere in this codebase.
       * ---------------------------------------------------------------- */

      // The type layer is built to be cast-free; `any` would silently undo it.
      '@typescript-eslint/no-explicit-any': 'error',

      // Unused code is either a mistake or dead weight. `_`-prefixed arguments
      // are the documented way to say "required by the signature, not needed".
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],

      // `import type` keeps type-only imports out of the emitted bundle, which
      // matters at the Server/Client boundary where an accidental value import
      // can drag server code into a client chunk.
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'separate-type-imports' },
      ],

      // `cond && <X/>` renders a literal `0` when `cond` is the number zero.
      // The brief mandates ternaries; this is the rule that enforces it.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'JSXExpressionContainer > LogicalExpression[operator="&&"]',
          message:
            'Use a ternary for conditional rendering. `&&` leaks falsy values such as 0 or "" into the DOM.',
        },
      ],
    },
  },

  {
    // Tests deliberately construct invalid values to prove the guards work.
    files: ['**/*.test.ts', '**/*.test.tsx', '**/*.test-d.ts', 'e2e/**'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-restricted-syntax': 'off',
    },
  },
];

export default config;
